### ISSUE TITLE
Custom placement of Tooltip's DOM node

### ISSUE THREAD

**Issue by rpearce** [darsain/tooltip#11]
Would you be interested in a pull request for the option to append the base tooltip node to someplace other than the `document.body`? We at [Articulate](https://www.articulate.com) are interested in utilizing this project and are thankful for your work, but we need just a bit more customization.

If the answer to the above is yes, will you please also add the MIT license to the project so that it covers our butts and so we could properly contribute?

**Comment by darsain** [comment]
What is the use case for attaching to other place than body?

And how do you image the API would look like?

---

Regarding license, it already is MIT. It's specified at the bottom of the readme, as well as in `componnet.json`.

Are you saying I really have to copy & paste the whole thing and place into a separate LICENSE.md for it to be valid? That would be annoying :disappointed:.

**Comment by rpearce** [comment]
Our use case is we have a parent container whose tooltip trigger is only visible when you hover over the parent container (or trigger it another way via touch on an iPad, for example). When your mouse leaves the parent container, the trigger and the tooltip should disappear.

When you hover and click on this trigger, the `Tooltip` library attaches a tooltip to the trigger; however, if you place your mouse inside of the tooltip, it is _not_ a child of the parent container, so the mouseLeave (whether CSS or JS) actions are triggered on the parent element and undesirable things happen.

If the tooltip was appended _within_ the parent container, then CSS attributes like `:hover` would recognize the element as a child element.

The alternative is to do this manually by selecting the tooltip node, cloning it, appending it where it needs to be, and then removing the one appended to `document.body`.

---------------------------------

For the API, I would presume that this is called  `appendTo` and is passed in with the `[options]` when instantiating via  `new Tooltip(...)`. For utility, `appendTo` could either be a string (for a selector) or a DOM element. If it is a string, we would call `document.querySelector(selector)` behind the scenes and get that DOM element; otherwise, if it was already passed a DOM element, it would just call `appendChild` on this element and pass the tooltip as an argument.

---------------------------------

Regarding the MIT license, it's not a deal breaker, but its inclusion is recommended by GitHub to "avoid ambiguity":
https://help.github.com/articles/open-source-licensing/#where-does-the-license-live-on-my-repository

**Comment by darsain** [comment]
Yah. I'll look into it hopefully this week. There'll need to be some more stuff done for positioning to work properly in this scenario.

I'll also add that damn license file :)

**Comment by rpearce** [comment]
Fantastic. Thank you :+1:

**Comment by darsain** [comment]
So I'm looking into this, and seeing that it's an edge case for which I'd have to do shenanigans inside Tooltip to make it work properly (like finding out which parent element is positioned otherwise than static, and using that as a position base. that would introduce some chaos).

It seems like the better way how to handle this would be delaying whatever logic you have in mouseleave to a 200ms or so from when it happened, while canceling it when mouse re-enters trigger areas.

Your use case wouldn't work really well with what you're asking anyway, because there is a gap between tooltip and the element it is attached to, so mouseleave would be fired anyway. Unless you'd restyle the tooltip offsets, but than arrow overlaps the attached element, which is not pretty.

Honestly, offsetting the logic and canceling it when mouse enters desired areas seems like a better and more robust solution than hacky change of an anchor element.

**Comment by rpearce** [comment]
Alrighty. Thanks for taking the time to look in to it.
